apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gamestore-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "api.yourdomain.com"
      http:
        paths:
          - path: /api/v1/auth/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 3001
          - path: /api/v1/games/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: game-service
                port:
                  number: 3002
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: game-service
                port:
                  number: 3002
          - path: /api/v1/orders/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: orders-service
                port:
                  number: 3003
          - path: /api/v1/reviews/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: reviews-service
                port:
                  number: 3004
    - host: "www.yourdomain.com"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 3000
    - host: "yourdomain.com"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 3000
