apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gamestore

resources:
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - solr.yaml
  - auth-service.yaml
  - game-service.yaml
  - orders-service.yaml
  - reviews-service.yaml
  - frontend.yaml
  - monitoring.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: gamestore
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/managed-by: kustomize
