apiVersion: v1
kind: ResourceQuota
metadata:
  name: gamestore-staging-quota
  namespace: gamestore-staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "100"
    services: "40"
    persistentvolumeclaims: "10"
